---
kind: Pod
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  restartPolicy: Never
  containers:
    - name: backend
      image: {{ .Values.image }}
      imagePullPolicy: IfNotPresent
      command:
        - /tardigrade
      # args: ["ACTION"]
      securityContext:
        runAsUser: 25643
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      env:
      - name: TEMPDIR
        value: /tmp
      - name: TMP
        value: /tmp
  volumes:
    - name: tempdir
      emptyDir: {}
      

