---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: {{ .Chart.Name }}
    alertroute: {{ .Values.alertroute }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-app
    port: 80
    protocol: TCP
    targetPort: app
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
