#!/bin/bash
set -eux

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common.sh"

if [ -n "${WORKSPACE:-}" ] || [ -n "${GITHUB_ACTIONS:-}" ]; then
  dockerwrap us.gcr.io/rsg-base-prod/golangci-lint:v1.47.3 golangci-lint run --verbose --timeout=5m
  exit $?
fi

# lint is exceptionally slow in docker on a mac. Let's run it directly
golangci-lint run --verbose
