#!/bin/bash
set -eux
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/common.sh" 

cd "${ROOT}"

# set path so this works in jenkins
export PATH="${ROOT}/bin":$PATH

for F in $(pando targets | grep -v local); do
    pando lint --validate --termination --target=$F
done
